### ISSUE TITLE
[Tracking] List or relevant phabs

### ISSUE THREAD

**Issue by physikerwelt** [MaRDI4NFDI/MaRDIRoadmap#113]
- [ ] https://phabricator.wikimedia.org/T339357
- [ ] https://phabricator.wikimedia.org/T287164
- [ ] https://phabricator.wikimedia.org/T234827
- [ ] https://phabricator.wikimedia.org/T138708
- [ ] https://phabricator.wikimedia.org/T141764
- [ ] https://phabricator.wikimedia.org/T372458
- [ ] https://phabricator.wikimedia.org/T387365
